### ISSUE TITLE
New feature: image zoom page

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#102]
Similar to the [browser extension](https://github.com/openseadragon/browser-extension), but set up as a webpage (for people who don't have the extension installed). 

Usecase: You run across an image like: 

http://orig00.deviantart.net/505e/f/2015/294/8/e/exoplanets_by_jaysimons-d9dv6th.jpg

...and you want to share an OpenSeadragon-ified version on Twitter or something. 

cc: @avandecreme

**Comment by iangilman** [comment]
Note that this is similar to http://zoom.it/ but without the server side component (so it's better for images under, say, 10,000px wide). 

cc: @aseemk @gasi @kenperkins @nein09

**Comment by avandecreme** [comment]
Yup, I actually had that in mind when building the extension, so it is already supported by the code in the [common directory](https://github.com/openseadragon/browser-extension/tree/master/common).
I should probably rename visualization.html to index.html though.

**Comment by iangilman** [comment]
@avandecreme Cool...so maybe all that needs to happen is setting up browser-extension to publish via gh-pages (and renaming that file)? It'll show up at http://openseadragon.github.io/browser-extension/common/. 

I guess the other nice thing would be to provide another page that provides an easy UI to enter a URL.

**Comment by avandecreme** [comment]
Possibly, that could be the same page to provide the URL.
If no image is provided in the URL, we would display an input text to enter one.
What do you prefer?

Also, maybe we should remove browser-extension from the URL. Maybe http://openseadragon.github.io/openseadragonizer ?

**Comment by iangilman** [comment]
Changing the URL like that would require changing the name of the repository, which is certainly something we could do. 

I'm fine with the same page providing UI if no URL is provided. I think I'd want the UI to look like it's part of the rest of the OpenSeadragon site. I suppose having that code on the page might make it heavier for the "url provided" use case. Also, if we host that UI in the browser-extension repository, we'd have code duplication with site-build (to make the page look consistent). 

So maybe the thing to do would be to have a page in site-build that has the site-build UI and a URL entry which then forwards you into the browser-extension page that actually displays the image.

**Comment by avandecreme** [comment]
>Changing the URL like that would require changing the name of the repository, which is certainly something we could do. 

I think we could also create an openseadragonizer folder inside the openseadragon.github.com repository which would contains the content of browser-extension/common.

>I think I'd want the UI to look like it's part of the rest of the OpenSeadragon site.

There isn't much place for styling in openseadragonizer because the viewer is taking the entire body area. Maybe having the URL input text as a popup reusing the same CSS than the website is enough?

**Comment by avandecreme** [comment]
I created a PR with that last idea: https://github.com/openseadragon/browser-extension/pull/12
This is still open for discussion, it just seems easier to code than to explain :)
And of course, I am a very bad designer so if you have any suggestions...

**Comment by iangilman** [comment]
Yeah, I guess now that you mention it, we can go minimal like that. 

I'm hesitant to add a publish step where we copy from browser-extension to the openseadragon.github.com repository...seems cleaner to keep it fully separate. On the other hand, the advantage would be we could be more selective about what we publish out of browser-extension, and we could include additional build steps if needed. I don't know...

**Comment by avandecreme** [comment]
>Yeah, I guess now that you mention it, we can go minimal like that. 

Excellent :)

>I'm hesitant to add a publish step where we copy from browser-extension to the openseadragon.github.com repository...seems cleaner to keep it fully separate.

Yup, if scripts from both browser-extension and site-build mess with openseadragon.github.com I can easily see how they could badly interact with each other.

>On the other hand, the advantage would be we could be more selective about what we publish out of browser-extension, and we could include additional build steps if needed.

I also prefer to have a url looking like http://openseadragon.github.io/openseadragonizer rather than http://openseadragon.github.io/browser-extension/common/

An other option would be to deploy from browser-extension to site-build but that is a lot of moving around...

**Comment by iangilman** [comment]
Well, let's try adding a `grunt publish` command for browser-extension that goes into ../openseadragon/github.com/openseadragonizer/ and see how we like it.
