### ISSUE TITLE
In the wild: New York Public Library

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#117]
Here's a recent announcement:

http://www.nypl.org/blog/2016/01/05/share-public-domain-collections

A lot of the content is done with OpenSeadragon. Of course we need to find a good example.

**Comment by TMUND** [comment]
Here are a couple I like, what do you think? 

http://digitalcollections.nypl.org/items/510d47e0-2be9-a3d9-e040-e00a18064a99

http://digitalcollections.nypl.org/items/8c108420-d56d-0131-4a50-58d385a7bbd0

There are a lot of galleries that are scroll wheel zoomable but some of the collections are just one click zoom unfortunately...let me know if you find something else that strikes your fancy or if I should keep looking :)

**Comment by iangilman** [comment]
Lighthouse please! :)
