### ISSUE TITLE
In the wild: installations

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#118]
Might be nice to have a section for places OpenSeadragon is used in installations (only available in person, not on the web). For instance:

https://twitter.com/MarinDaddy/status/685556928726962176

**Comment by TMUND** [comment]
Any idea where you'd like to add this section. Also, how do we know when an installation no longer exists/isn't using OpenSeadragon? Do we know if there is more than one place using OSD on location?

**Comment by iangilman** [comment]
I'm thinking make a new section at the bottom of the "in the wild" page. I think it's fine if installation listings go out of date, as it's still a record of where they had been (though of course if someone alerts us we can certainly remove them as needed).

If I recall correctly, @crswll is responsible for some installations as well; perhaps he can fill us in on those. Also, maybe once we get the first one in we can ask if anyone knows more via Twitter and Gitter.

**Comment by crswll** [comment]
We currently have one installation active using OpenSeadragon as far as I know. It's at The Wadsworth museum.

Here's the only thing they seem to mention on the site about it:
https://thewadsworth.org/event/art-curiosity-cabinets-historical-contemporary-perspectives/

And here's a mention of the renovation that also mentions the interactive:
http://hyperallergic.com/237531/a-worthy-renovation-for-the-wadsworth-atheneums-european-art-galleries/

As more come through I'll let you know!

**Comment by iangilman** [comment]
@crswll Awesome, thank you!

**Comment by iangilman** [comment]
Closed by #125. 

@crswll It's at the bottom of: 

http://openseadragon.github.io/examples/in-the-wild/

Can you verify we have the right info? And of course keep us posted in the future!
