### ISSUE TITLE
Broken link on openseadragon.github.io/docs/

### ISSUE THREAD

**Issue by chris-engberg** [openseadragon/site-build#142]
On: http://openseadragon.github.io/docs/

The link for OpenSeadragon() in paragraph 1 is currently:
http://openseadragon.github.io/docs/module-OpenSeadragon.html
leading to a 404

Should be:
http://openseadragon.github.io/docs/#module-OpenSeadragon.html

**Comment by avandecreme** [comment]
Thanks for catching this.
Actually I removed the module so it should link to the namespace I think: http://openseadragon.github.io/docs/OpenSeadragon.html
However, the `OpenSeadragon` function is not documented (anymore?) anywhere.
Maybe adding a `@namespace OpenSeadragon` here would add that method in the doc: https://github.com/openseadragon/openseadragon/blob/master/src/openseadragon.js#L684 ?

**Comment by iangilman** [comment]
The shortcut is documented in the entry for the constructor: 

http://openseadragon.github.io/docs/OpenSeadragon.Viewer.html#Viewer

I've updated the docs to point there (and also to mention that there are two ways to do it):

http://openseadragon.github.io/docs/

@chris-engberg Thanks again for spotting this!

@avandecreme I'd certainly be up for trying the `@namespace OpenSeadragon` if you want to give it a try.
