### ISSUE TITLE
Create example page for Zoomify tile source

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#148]
...and link it from the front page of course.

I suppose to do this we'll need a nice image in Zoomify format. @foobarable any thoughts on where to get such a thing?

**Comment by foobarable** [comment]
I could provide you with images like that:

https://gp3.mpg.de/viewer

Or, if you have an image of your choice, I can zoomify (no pun intended) it.

**Comment by iangilman** [comment]
Nice! While cool, I'm concerned those images might creep some people out.

I guess we could zoomify the cathedral photo from the OSD front page. Send me an email at ian@iangilman.com and we can pass files back and forth. Thank you for helping with this!
