### ISSUE TITLE
Add server options to "Creating" page

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#162]
In addition to listing tools that create zoomable images, we should add a list of servers that can serve zoomable images, including: 

* http://iipimage.sourceforge.net/
* https://medusa-project.github.io/cantaloupe/

...to this page: 

http://openseadragon.github.io/examples/creating-zooming-images/

**Comment by kittarlin** [comment]
Page update in progress.

**Comment by iangilman** [comment]
This has been fixed by #179.
