### ISSUE TITLE
[bower.json] invalid-meta The "main" field cannot contain minified files

### ISSUE THREAD

**Issue by adgoncal** [openseadragon/site-build#166]
I just noticed a WARN during bower install:
> invalid-meta The "main" field cannot contain minified files

Bower spec: https://github.com/bower/spec/blob/master/json.md#main
> Image and font files may be used or referenced within the JS or Sass files, but are not main files as they are not entry-points.
> 
> - Use source files with module exports and imports over pre-built distribution files.
> - **Do not include minified files.**
> - Do not include assets files like images, fonts, audio, or video
> - Filenames should not be versioned (Bad: package.1.1.0.js; Good: package.js).
> - Globs like js/*.js are not allowed.

Reading the spec I am not sure whether the source map file should be there.

Discussion of the spec for _main_: https://github.com/bower/bower/issues/393

**Comment by iangilman** [comment]
Okay, sounds like it should just be the unminified file and not the map (which is only applicable to the minified file).

    "built-openseadragon/openseadragon/openseadragon.js"

@adgoncal Would you be up for making that change?
