### ISSUE TITLE
Add HDMake to "creating" page

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#168]
http://research.microsoft.com/en-us/um/redmond/groups/ivm/HDView/HDMake.htm

**Comment by kittarlin** [comment]
The above link doesn't appear to be viable.  I've found this one: 

https://www.microsoft.com/en-us/research/search/?q=hdmake

But the description is cut off and the file type generated is not obvious.  Do you know if it makes DZIs or something else?

**Comment by iangilman** [comment]
Looks like maybe this is a better link:

https://www.microsoft.com/en-us/download/details.aspx?id=52341

That's just the 64-bit version, but I think that's all we need today.

The description says:

> The HD View Utilities are a set of tools that help you create stunning HD View images. This package includes a Photoshop plug-in that enables you to export an HD View Web page or a cross-platform Silverlight Deep Zoom page from within Photoshop. Also included is hdmake, which a simple command-line utility that provides the same function for users who don’t own Photoshop.

...so that means it creates DZI.

**Comment by kittarlin** [comment]
Thanks.  Update in progress.

**Comment by iangilman** [comment]
This has been fixed by #179.
