### ISSUE TITLE
Beehive collective poster is down

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#175]
http://beehivecollective.org/posterViewer/?poster=mr

@jrochkind is it down for good? I love that thing! It would be sad for it to go away entirely :(

**Comment by jrochkind** [comment]
Thanks for the kind words! (Although the Beehive Collective gets all credit for the art, I get credit for the technical implementation, along with OSD!)  I loved it too!

I'm afraid I don't know, the beehive collective website (WordPress) got hacked, and they didn't have a good backup, and they're figuring out what to do next. 

If you know anyone interested in helping them make a new website for cheap, I can put you in touch. :)

Otherwise, we do have the source of the JS viewer on github, and I do still have a copy of the original source graphics on my own HD, and they are licensed for redistribution... perhaps I'll ask them if they mind if you or I put it up again somewhere. Are you interested in doing the work? :)

**Comment by jrochkind** [comment]
(Also, I have a new OSD-based project of cool stuff to share, that I'll let you know about when it goes public in a couple months. :)  OSD is pretty great to work with!)

**Comment by jrochkind** [comment]
The bees say they don't mind if I/we put it up somewhere ourselves, as long as it links back to the still existing beehive web properties (facebook page, web store). 

Any interest in collaborating? :)

**Comment by jrochkind** [comment]
i'm thinking this can be done for free somewhere since it's just static content, maybe github pages, not sure if there's a way to find some free DNS too to give it a nice url.

**Comment by iangilman** [comment]
Wonderful! Yes, GitHub Pages is probably a great choice. We host all of our sample images that way, for instance. 

I don't think I'd even worry about getting a special domain for it, though of course if there's a free way to do that, why not? Otherwise it's more important that it just be up somewhere. 

So, how about GitHub Pages on your GitHub account? Something like http://jrochkind.github.io/beehive-collective ?

I'm happy to help... what needs doing?

**Comment by jrochkind** [comment]
Done. http://jrochkind.github.io/beehive_poster_viewer/

**Comment by iangilman** [comment]
Beautiful!! I do love this one. Would you be up for fixing the URL in https://github.com/openseadragon/site-build/blob/master/www/in-the-wild.html?

Btw, I'm noticing the mouse wheel zoom isn't as smooth as it is with the newer versions of OSD, and sure enough it looks like you're using version 1.1.1. What would you think about upgrading to the latest?

**Comment by jrochkind** [comment]
Good idea, an OSD upgrade, yeah. Not sure when I'll get to it. PR's welcome. :)

**Comment by iangilman** [comment]
Okay! It's a race to see who finds some free time first ;)

Thanks again for getting this back up!

**Comment by kittarlin** [comment]
The original link at the top of this thread appears to be working again.  At least, I can get there from the link on the In The Wild page...

**Comment by jrochkind** [comment]
yeah, it is working again at beehivecollective.org at the moment.

**Comment by kittarlin** [comment]
Great!  @jrochkind  Do you think we should leave the In The Wild page with the link it has (the collective) or would it be more stable long-term to change it to point to your version on GitHub?

**Comment by jrochkind** [comment]
As long as it is actually working, the beehivecollective.org link is better, they are the ones whose art it actually is.

**Comment by iangilman** [comment]
Cool... I'm glad to hear it's back up! Also @jrochkind I see you updated the OSD version... nice and smooth now :)

**Comment by jrochkind** [comment]
yup, more appropriate display on 'retina' screen too I think.

**Comment by iangilman** [comment]
Indeed! :)
