### ISSUE TITLE
yet more "in the wild"

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#194]
https://benihassan.com/dictionary/Kanawati-Evans-BH1-Pl-07a-Beni-Hassan-Khnumhotep-II-Tomb-3-Chapel-Inscription-East-wall-Lower-section-Wall/

**Comment by iangilman** [comment]
https://wellcomecollection.org/works/jgeykh4m or some related from that collection.

**Comment by iangilman** [comment]
Wellcome collection has been added :)

**Comment by iangilman** [comment]
http://beta.biblissima.fr/fr/ark:/43093/ifdata68b8958d6efb2c5b0d9e670d185dcd38a01b1f57

See https://twitter.com/biblissima/status/1016298710974820352

**Comment by iangilman** [comment]
All of the "Sites Using Zoomable" listed here: 

https://zoomable.ca/

**Comment by kittarlin** [comment]
The best of the Zoomable sites are included.  I didn't include those that didn't have an OSD image above the fold.   The Biblissima site was already on the page.  Also, WebWallWhispers.  Embers and Beni Hassan links added.
