### ISSUE TITLE
Rotation example page

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#25]
Now that @robhobbes's https://github.com/openseadragon/openseadragon/pull/185 has landed, we should add an example page for the rotation feature.

**Comment by sdellis** [comment]
I'm having trouble implementing rotation and would love to see an example if this is possible.  Is the rotation data supposed to be included as a property for each object in [the tileSources array shown here](http://openseadragon.github.io/examples/tilesource-iiif/)?

**Comment by robhobbes** [comment]
Rotation data should'nt need to be included. All you should need to do to rotate is to call ```setRotation(degrees)``` on the viewport object.

**Comment by sdellis** [comment]
Thanks for the reply @robhobbes .  Yes, that's what I'm doing, but when I do that the image gets cropped within the viewport.  [Here's an example](http://libphp-prod.princeton.edu/versailles/item/875) of what I'm talking about.

**Comment by robhobbes** [comment]
@sdellis Hmmm. I suppose that it is likely a bug. I haven't touched the code in over a year and I'm not really in a place to work on it at this point in my life.

**Comment by sdellis** [comment]
I'm happy to look into it and can submit a fix.  I imagine that when rotated 90 or 270 we just need to swap the height and width of the image wherever it gets drawn.  @iangilman Should I create a new issue for this?

**Comment by iangilman** [comment]
Interesting! Yes, please create an issue in the OpenSeadragon repository. It would be great if you could look into it as well. :-)
