### ISSUE TITLE
Directory of OpenSeadragon plugins

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#26]
@dgutman has a plugin. Surely there will be more.

**Comment by MindFreeze** [comment]
New plugin: https://github.com/picturae/openseadragonselection
This could be used for cropping. I will be using it to provide coordinates for external cropping.
It is still a work in progress.

**Comment by iangilman** [comment]
@MindFreeze Cool! Are you ready to share it more widely? If so, can you make a pull request to add it into the front page? 

https://github.com/openseadragon/site-build/blob/master/www/index.html#L146

**Comment by MindFreeze** [comment]
New one: https://github.com/picturae/openseadragonrgb
Pull request to site-build submitted.
