### ISSUE TITLE
Update info on using zoom.it tiles

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#27]
From @aseemk, one of the original authors of zoom.it:

https://twitter.com/aseemk/status/374011428581036032

The info needs to be added to:

https://github.com/openseadragon/site-build/blob/master/www/tilesource-zoomit.html

**Comment by kittarlin** [comment]
Zoom.it doesn't exist any more.

**Comment by iangilman** [comment]
Indeed. We can resurrect this when ZoomHub has a proper API again. /cc @gasi @aseemk

**Comment by gasi** [comment]
For completeness: Zoom.it / ZoomHub has a read-only API and support for consuming DZIs fully compatible with the old Zoom.it. Return of the submission UI and API is TBD.

**Comment by iangilman** [comment]
@gasi Good point... Currently we have the Zoom.it page hidden (not linked from anywhere) but it still exists:

http://openseadragon.github.io/examples/tilesource-zoomit/

My feeling is it's not worth bringing back until submission is possible again, since presumably the people who are already using ZoomHub are already set up. What do you think?

**Comment by gasi** [comment]
@iangilman Makes sense 👍
