### ISSUE TITLE
Flip toggling along with maxZoomLevel problem

### ISSUE THREAD

**Issue by mikfuro3** [openseadragon/site-build#284]
Using the maxZoomLevel property to increase the zoom limit and flipping the image through toggleFlip method, causes an "unflip" effect when reaching the maximum zoom.
Here's the codepen sample: https://codepen.io/mikifufu/pen/qBGNxPz
To reproduce, you simply need to fully zoom the image.

**Comment by iangilman** [comment]
Thank you for reporting! This is actually the wrong repository... Issues with OSD (not the OSD site) should be reported in https://github.com/openseadragon/openseadragon.

At any rate, this bug has been fixed on OSD master: https://github.com/openseadragon/openseadragon/pull/2364 If you want the fix right away you can build from master. We're currently in a long development cycle on the new WebGL drawer, so we're not expecting to make a new release in the short-term.

**Comment by mikfuro3** [comment]
Sorry for the oversight, I don't know how I ended up in this repo.
However, thanks for the support!
