### ISSUE TITLE
Getting started or FAQ

### ISSUE THREAD

**Issue by mdjasper** [openseadragon/site-build#45]
I've received a bit of help implementing OpenSeadragon by asking questions here on GitHub -- and it dawned on me that perhaps there could be some extension to the getting started page, or frequently asked questions page for first-time users like myself.  I've cloned down the site-build repo to make some changes myself, but I don't want step on anyone's toes. Would this sort of contribution be welcome from a first-time user? Are there any existing plans for this sort of feature, or anyone else already working on it?

**Comment by iangilman** [comment]
Looks like this didn't happen, so I'm closing it. The new FAQ issue is https://github.com/openseadragon/openseadragon/issues/2368.

**Comment by iangilman** [comment]
@mdjasper If you have any old work in progress on this front laying about on your harddrive, I'd love to see it. 😄
