### ISSUE TITLE
Add list of sites that use our tech

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#6]
... to our website

**Comment by iangilman** [comment]
http://alexbartl.de/alex/panorama.html

**Comment by MartinPluta** [comment]
http://www.zoosphere.net
http://www.zoosphere.net/sequence/3

**Comment by iangilman** [comment]
http://zoomable.ca/

**Comment by iangilman** [comment]
http://annotorious.github.io/demos/openseadragon-preview.html

**Comment by iangilman** [comment]
http://nladom-test.nla.gov.au/nla.obj-41292842/view from @terenceingram

**Comment by jorntx** [comment]
The Danish Newspaper Online Archive - partial public access:

http://www2.statsbiblioteket.dk/mediestream/avis/search/horse/allowedonly/true?locale=en

**Comment by iangilman** [comment]
Believe it or not, after years of anticipation, I've finally made this page! 

http://openseadragon.github.io/examples/in-the-wild/

Thanks again to everyone who contributed! Keep the suggestions coming; they'll be much easier to add now that we have a real page.

**Comment by avandecreme** [comment]
Nice!

**Comment by acdha** [comment]
@iangilman That looks great – looking forward to seeing the list keep growing!

**Comment by gechols** [comment]
FamilySearch - the world's leading genealogical research site - uses OSD as the image viewer for the vast range of its historical records.

https://familysearch.org/pal:/MM9.3.1/TH-1942-27779-1718-28?cc=2000219

**Comment by iangilman** [comment]
@gechols Awesome, thank you! Added to the "History" section: 

http://openseadragon.github.io/examples/in-the-wild/

**Comment by AKlein920** [comment]
EarthCam's Public Player (custom media player created for EarthCam's camera content) - OSD is used to view megapixel archive images taken by cameras. My former team built a cool image comparison feature that can be activated by clicking the button on the lower right-hand side of the tool bar. 

https://public.earthcam.net/earthcam/earthcampus/gigapixelcam_x1/view_1

@arfusop

**Comment by iangilman** [comment]
@AKlein920 Cool! Thank you for adding this. I've posted it to the active version of this issue: 

https://github.com/openseadragon/site-build/issues/200#issuecomment-522116595

At some point someone will hopefully get around to updating the "in the wild" page from that issue. If you want to make it happen sooner for your project, feel free to make a PR against this file:

https://github.com/openseadragon/site-build/blob/master/www/in-the-wild.html
