### ISSUE TITLE
Add link to file format on "Creating" page

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#66]
...for people who want to write their own generator.

I figure this is the link to use: 

https://msdn.microsoft.com/en-us/library/cc645077%28v=vs.95%29.aspx

**Comment by kittarlin** [comment]
This is a better link:

https://github.com/openseadragon/openseadragon/wiki/The-DZI-File-Format

Also, it should probably go at the bottom of the page, after the table.  "If none of these options meet your needs, you can create your own tile-generating tool.  See <<link>> for more information the DZI format."

**Comment by kittarlin** [comment]
Page update in progress.

**Comment by iangilman** [comment]
This has been fixed by #179.
