### ISSUE TITLE
add owlstand to "in the wild"

### ISSUE THREAD

**Issue by iangilman** [openseadragon/site-build#84]
Main page: http://www.owlstand.com/

Example: http://www.owlstand.com/exhibition/room/9e83a1f3-2b6c-4ac2-bd1d-36b03871d0b4 (or whatever you like)

@TMUND  care to take this? :-)

**Comment by TMUND** [comment]
Will do :)

**Comment by TMUND** [comment]
Oooh multi-image demo :D

**Comment by iangilman** [comment]
Fixed by #85
