### ISSUE TITLE
Add The Human Protein Atlas to "in the wild"

### ISSUE THREAD

**Issue by perog** [openseadragon/site-build#93]
The Human Protein Atlas version 14 now includes a mouse brain viewer based on openseadragon. 

Main site:
http://www.proteinatlas.org/

Example:
http://www.proteinatlas.org/ENSG00000213463-SYNJ2BP/tissue/mouse+brain

**Comment by iangilman** [comment]
@perog Very cool! 

@TMUND Can you add this?

**Comment by msalsbery** [comment]
@perog Nice thanks!

**Comment by iangilman** [comment]
Fixed by #96

**Comment by iangilman** [comment]
...and published: http://openseadragon.github.io/examples/in-the-wild/
